### ISSUE TITLE
get_iset_conll_feat returns other=HASH(0x30ae3c40)

### ISSUE THREAD

**Issue by martinpopel** [ufal/treex#11]
`Write::CoNLLX` uses `$anode->get_iset_conll_feat` to print the `feat` column (if `feat_attribute eq 'iset'`). Interset can contain feature `other` which is a hash reference and [the current code](https://github.com/ufal/treex/blob/08549e4210c0432b32f7375ff9e13a0974168bc3/lib/Treex/Core/Node/Interset.pm#L237-L252) prints the hash reference address, e.g. 'HASH(0x30ae3c40)', which is probably not the intended behavior.

Simple fix would be to skip `other` and `tagset` feature (as it is done in [the `get_iset_values` method](https://github.com/ufal/treex/blob/08549e4210c0432b32f7375ff9e13a0974168bc3/lib/Treex/Core/Node/Interset.pm#L205-L212)).
I think a better fix would be to delete these methods completely and use `$anode->iset->some_serialization_method`. Unfortunately, I don't see any suitable method in [Lingua::Interset::FeatureStructure](https://metacpan.org/pod/Lingua::Interset::FeatureStructure). If it is missing on purpose, I'll do the 'simple fix' above.

**Comment by dan-zeman** [comment]
Thanks for reporting, this is a legacy of Interset 1 being once used in Treex. Interset 2.047 will have two new methods that can replace some code in Treex::Core::Node::Interset. And it should fix the bug as well. I am now adapting the Treex code in a separate branch.
