### ISSUE TITLE
SetDocOrds with multiple selectors

### ISSUE THREAD

**Issue by ptakopysk** [ufal/treex#2]
treex/lib/Treex/Block/A2T/SetDocOrds.pm does not support multiple selectors, neither specified as selector=all nor as selector='src,ref'

**Comment by martinpopel** [comment]
What is the expected output?
Both zones having independent `doc_ord` numbers starting from 1 (as is the result of calling the block twice in the scenario: once with `selector=src`, once with `selector=ref`)? Or each node in the document having a unique `doc_ord`?
CC: @michnov
