### ISSUE TITLE
Frontier::Client is missing

### ISSUE THREAD

**Issue by martinpopel** [ufal/treex#43]
PT2EN translation is not replicable because module Frontier::Client is missing in the repository.
It should be perhaps renamed to Treex::Tool::LXSuite::Frontier::Client.
It is needed in Treex::Block::W2A::PT::LXSuite.

**Comment by joaoantonioverdade** [comment]
Please install the Frontier package.
http://search.cpan.org/~rtfirefly/Frontier-RPC/lib/Frontier/Client.pm
