### ISSUE TITLE
Read::PDT cannot read PDT 2.5

### ISSUE THREAD

**Issue by ptakopysk** [ufal/treex#57]
Read::PDT cannot read PDT 2.5, although the documentation says it can. Please either fix the functionality or the documentation, according to what is intended.
```
treex -Lcs Read::PDT from=/ha/work/people/stepanek/PDT2.5/data/tamw/dtest/mf930709_062.t.gz
```
...
```
Error occured while reading '/ha/work/people/stepanek/PDT2.5/data/tamw/dtest/mf930709_062.t.gz' using backend Treex::PML::Backend::PML:
Couldn't open PML schema file 'tdata_25_schema.xml'
File does not exist: tdata_25_schema.xml
```

**Comment by tuetschek** [comment]
This was trivial (schemas for PDT2.5 were missing). I added them in 4ac8e85 , @ptakopysk, check if it is fixed.

**Comment by martinpopel** [comment]
@tuetschek you were exactly 15 seconds faster than me:-).

**Comment by tuetschek** [comment]
@martinpopel: I wasn't expecting you to be online, everyone is supposed to be on holiday :-).

**Comment by ptakopysk** [comment]
Thanks!
