### ISSUE TITLE
CPAN dependencies of Treex::Core

### ISSUE THREAD

**Issue by dan-zeman** [ufal/treex#59]
PerlIO::Util failed to install under Strawberry Perl in Windows. That means Treex::Core cannot be installed, which in turn means that Tred cannot use the Easytreex extension and cannot work with treex files.

Is it possible to get rid of this module?

(I tried this twice but neither worked. First with Perl 5.16, which comes with Tred and reportedly is needed for Tred. And then also with the newest 64bit Perl 5.24 – if this worked, Tred might still not like it because of the unsupported Perl version, but it did not work anyway. It was not my computer so I do not know whether I can repeat it; but anyway, I had to install Tred+Treex for out-of-ÚFAL colleagues several times in the past, and the fight with CPAN was always extremely frustrating.)

**Comment by martinpopel** [comment]
PerlIO::Util installation tests are known to fail [on Windows](https://rt.cpan.org/Public/Bug/Display.html?id=71549) or [on Perl > 5.14](https://rt.cpan.org/Public/Bug/Display.html?id=74539). I agree it's frustrating, but obviously not frustrating enough to force someone to substitute PerlIO::via::gzip with PerlIO::gzip (or something that works also on Windows) in Treex (or to fix the problems in [source](https://github.com/gfx/Perl-PerlIO-Util)).

This is the reason why the [Treex installation guide](http://ufal.mff.cuni.cz/treex/install.html) suggest to skip test for this module with `cpanm -n PerlIO::Util`. Have you followed the guide? If you just clicked on EasyTreex extension in TrEd, [it should](https://svn.ms.mff.cuni.cz/projects/tectomt_devel/browser/trunk/treex/devel/easytreex_tred_extension/easytreex/contrib/easytreex/contrib.mac#L55) also skip the tests.

**Comment by dan-zeman** [comment]
Thanks @martinpopel, I actually know the guide but forgot to look at it, since Treex was not the main thing I was trying to install this time.

Running `cpanm -n PerlIO::Util` helped (before reading the guide I thought that the `--force` option to cpanm would do the same job but apparently it didn't).

After installing `PerlIO::Util` the rest went almost smoothly, I only had to hack a bit one other issue, `ExtUtils/PL2Bat.pm` was needed to "configure" `Module::Build::Tiny` but it was not identified as its dependency, so I had to figure this out from `build.log` and install it with a separate call to cpanm. You may want to include this info in the guide (for the users who don't forget to read it :)).

**Comment by martinpopel** [comment]
OK, thanks for reporting. I've filled [an issue](https://rt.cpan.org/Ticket/Display.html?id=117926) for this Windows-specific problem.
